### ISSUE TITLE
Version 2.0.13 not compatible with Groovy 3

### ISSUE THREAD

**Issue by sagrawal31** [grails-plugins/grails-quartz#110]
## Description

Grails 4.1.0.M1 uses Groovy 3 as per `gradle.properties`-

```
grailsVersion=4.1.0.M1
groovyVersion=3.0.3
gorm.version=7.1.0.M2
```

When we install this plugin and run the application, it fails on the startup-

```
java.lang.IllegalAccessError: tried to access method grails.plugins.quartz.config.TriggersConfigBuilder.createNode(Ljava/lang/Object;Ljava/util/Map;Ljava/lang/Object;)Ljava/lang/Object; from class grails.plugins.quartz.config.TriggersConfigBuilder$createNode
        at grails.plugins.quartz.config.TriggersConfigBuilder$createNode.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at grails.plugins.quartz.config.TriggersConfigBuilder.createNode(TriggersConfigBuilder.groovy:245)
        at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:90)
        at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:413)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:337)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at com.wizpanda.file.DeleteMarkedFileJob$__clinit__closure1.doCall(DeleteMarkedFileJob.groovy:16)
        at com.wizpanda.file.DeleteMarkedFileJob$__clinit__closure1.doCall(DeleteMarkedFileJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at grails.plugins.quartz.config.TriggersConfigBuilder.build(TriggersConfigBuilder.groovy:52)
        at grails.plugins.quartz.DefaultGrailsJobClass.evaluateTriggers(DefaultGrailsJobClass.java:56)
        at grails.plugins.quartz.DefaultGrailsJobClass.getTriggers(DefaultGrailsJobClass.java:109)
        ...
```

When downgrading to Grails `4.0.4`, this works. So as per my limited knowledge of changes in Grails 4, it seems to be an issue with Groovy 3 only (as I read from https://stackoverflow.com/a/7076502/2405040)

## Environment

- macOS Catalina
- JDK 1.8.0_9

**Comment by sagrawal31** [comment]
Any update here?

**Comment by sagrawal31** [comment]
This no longer seems to be an issue for me with Grails 5.2.3.
