### ISSUE TITLE
"org.quartz.SchedulerConfigException: DataSource name not set" even when jdbcStore is set to false

### ISSUE THREAD

**Issue by vijeetgv** [grails-plugins/grails-quartz#32]
Just upgraded to Grails 2.4.3 & also upgraded quartz to 1.0.2 & getting this exception. The configuration seems fine:
```
quartz {
    jdbcStore = false
    autoStartup = true
}
```
but upon running the application it throws down this:
```
Caused by: org.quartz.SchedulerConfigException: DataSource name not set.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.initialize(JobStoreSupport.java:638)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.initialize(JobStoreTX.java:57)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1333)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:597)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:480)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 25 more
```

**Comment by psoares** [comment]
Is that the only configuration you have ? I have a similar issue, but my config is :

```
quartz {
    autoStartup = true
    jdbcStore = true
    waitForJobsToCompleteOnShutdown = false
	
	// Allows monitoring in Java Melody
    exposeSchedulerInRepository = true

    props {
		
		threadPool.'class' = 'org.quartz.simpl.SimpleThreadPool'
		threadPool.threadCount = 10
		threadPool.threadPriority = 7
        threadPool.threadNamePrefix = 'quartz-job-thread-'
        threadPool.threadsInheritContextClassLoaderOfInitializingThread = true

//        scheduler.classLoadHelper.class = 'org.quartz.simpl.CascadingClassLoadHelper'
//        scheduler.threadsInheritContextClassLoaderOfInitializer = true
        scheduler.skipUpdateCheck = true
        scheduler.instanceId = 'AUTO'
        scheduler.idleWaitTime = 1000

        jobStore.'class' = 'org.quartz.impl.jdbcjobstore.JobStoreTX'
        jobStore.driverDelegateClass = 'com.genomequest.kwsearch.MysqlJDBCDelegate'
        jobStore.useProperties = false
        jobStore.tablePrefix = 'QRTZ_'
        jobStore.isClustered = true
        jobStore.clusterCheckinInterval = 5000
        jobStore.misfireThreshold = 60000

		plugin.shutdownhook.'class' = 'org.quartz.plugins.management.ShutdownHookPlugin'
		plugin.shutdownhook.cleanShutdown = true

    }
}

environments {
	development {
		quartz {
            scheduler.instanceName = 'quartz_dev'
		}
	}
	
    stage {
        quartz {
			props {
				scheduler.instanceName = 'quartz_stage'
			}
        }
    }
	
	test {
		quartz {
			autoStartup = false
			jdbcStore = false
            jobStore.driverDelegateClass = 'org.quartz.impl.jdbcjobstore.StdJDBCDelegate'
			
			// Allows monitoring in Java Melody
			exposeSchedulerInRepository = false
			
			props {
				scheduler.instanceName = 'quartz_test'
                                jobStore.isClustered = false
			}
		}
	}
	
	production {
		quartz {
			props {
				scheduler.instanceName = 'lq_quartz_prod'
			}
		}
	}
}
```

And my StackTrace : 

```
2015-11-06 14:56:18,215 -0500 [main] WARN  JobStoreTX:743  - Database connection shutdown unsuccessful.
java.sql.SQLException: There is no DataSource named 'null'
	at org.quartz.utils.DBConnectionManager.shutdown(DBConnectionManager.java:135)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.shutdown(JobStoreSupport.java:741)
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:760)
	at org.quartz.impl.StdSchedulerFactory.shutdownFromInstantiateException(StdSchedulerFactory.java:1372)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1356)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
        ...
```

**Comment by rvanderwerf** [comment]
this is apparently due to a default setting was changed if no store is set it defaults of the data source.

**Comment by vijeetgv** [comment]
@rvanderwerf  is there some other config changes necessary to get this working? Maybe RamJobStore? What'd be the best pattern in QuartzConfig.groovy to do so?

**Comment by rvanderwerf** [comment]
I will be working on a patch soon to fix that and a couple other issues on here. Stay tuned!

**Comment by vijeetgv** [comment]
Thanks!

**Comment by rvanderwerf** [comment]
so I can tell you the 'jdbcStore' in quartz {} is not hooked up to anything. The main problem atm is if your app has hibernate plugin installed, it will try to hook up the jdbc stuff anyways. Using the property 'org.quartz.jdbcStore' -might- work but seeing the looks to to detect hibernate plugin that is doubtful atm until we get a fix out.

**Comment by rvanderwerf** [comment]
checked in a fix to master. If you set jdbcStore = false, it will use Ram Job Store.  It was using JDBC no matter what you did before which was related to issues #37 (also needed a few other checks).

**Comment by vijeetgv** [comment]
Thanks @rvanderwerf !

**Comment by vijeetgv** [comment]
@rvanderwerf this seems to have gone into version 2.x of the plugin. Is it possible to do a version which can be used with grails 2.5.x ?
